# Generated by Django 5.2.7 on 2026-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_amount_minor_transaction_settlement_amount_minor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash_dedupe',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
