# Generated by Django 5.2.13 on 2026-05-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_hash_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Bank-assigned unique transaction ID (e.g. QFX FITID). Null for formats that do not provide one.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PARSED', 'Parsed'), ('ENRICHED', 'Enriched'), ('NEEDS_REVIEW', 'Needs review')], default='PARSED', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash_dedupe',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text="The financial institution that issued this account, e.g. 'Chase'.", max_length=64)),
                ('account_identifier', models.CharField(help_text='Identifier used by the institution, e.g. ACCTID from a QFX file.', max_length=128)),
                ('account_type', models.CharField(choices=[('CREDIT_CARD', 'Credit card'), ('CHECKING', 'Checking'), ('SAVINGS', 'Savings')], max_length=16)),
                ('default_currency', models.CharField(help_text="The account's own currency; the currency transactions settle in.", max_length=3)),
                ('nickname', models.CharField(blank=True, help_text='Optional user-facing label.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'account_identifier'), name='uniq_account_institution_identifier')],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The account this transaction belongs to. Nullable for legacy rows created before accounts were modeled.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.account'),
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=1024)),
                ('parser_name', models.CharField(max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('ledger_balance_minor', models.BigIntegerField(blank=True, help_text="Statement-reported ledger balance, in minor units of the account's default currency.", null=True)),
                ('available_balance_minor', models.BigIntegerField(blank=True, help_text="Statement-reported available balance, in minor units of the account's default currency.", null=True)),
                ('transaction_count', models.IntegerField(blank=True, help_text='Number of transactions parsed from the statement.', null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='transactions.account')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.statementimport'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_transaction_id__isnull', False)), fields=('account', 'source_transaction_id'), name='uniq_transaction_account_source_id'),
        ),
    ]
