
version: "3.9"
services:
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    env_file:
      - ../.env.example
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: unified_txns
      POSTGRES_USER: unified_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
